name: ChatPing
main: com.notoriousdev.chatping.ChatPing
version: 1.1
author: BranicYeti
website: http://www.notoriousdev.com

permissions:
  chatping.ping:
    default: true
  chatping.ping.exempt:
    default: false
